#!/bin/bash
#
# Integrate Crime Camera Widget with External App
#

EXTERNAL_APP="http://192.168.0.169:8421"
WIDGET_FILE="/home/matt/r510-command-center/crime-cam-integration-widget.html"

echo "═══════════════════════════════════════════════════════"
echo "Crime Camera Integration with External App"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📍 External App: $EXTERNAL_APP"
echo "📄 Widget File: $WIDGET_FILE"
echo ""
echo "Integration Options:"
echo ""
echo "1️⃣  IFRAME EMBED (easiest)"
echo "   Add this to your app's HTML:"
echo ""
echo "   <iframe src=\"file://$WIDGET_FILE\" "
echo "           width=\"100%\" "
echo "           height=\"600px\" "
echo "           frameborder=\"0\"></iframe>"
echo ""
echo "2️⃣  SIDE-BY-SIDE VIEW"
echo "   Open both in Chrome with split screen:"
echo ""
echo "   google-chrome --new-window \\"
echo "     '$EXTERNAL_APP' \\"
echo "     'file://$WIDGET_FILE' &"
echo ""
echo "3️⃣  POPUP WINDOW"
echo "   Open widget as popup from your app's JavaScript:"
echo ""
echo "   window.open('file://$WIDGET_FILE', 'cameras', "
echo "     'width=800,height=600');"
echo ""
echo "4️⃣  API INTEGRATION"
echo "   Call the Bridge API directly from your app:"
echo ""
echo "   // Get incidents"
echo "   fetch('http://100.103.3.35:9000/api/incidents')"
echo "     .then(r => r.json())"
echo "     .then(data => console.log(data.incidents));"
echo ""
echo "   // Get cameras near a location"
echo "   fetch('http://100.103.3.35:9000/api/cameras/nearby?lat=41.259&lon=-95.933')"
echo "     .then(r => r.json())"
echo "     .then(data => console.log(data.cameras));"
echo ""
echo "   // Get camera feed"
echo "   <img src=\"http://100.103.3.35:4173/api/cctv/frame/CAMERA_ID\" />"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "Quick Demo:"
echo "═══════════════════════════════════════════════════════"
echo ""
read -p "Open widget in Chrome now? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    DISPLAY=:0 google-chrome "file://$WIDGET_FILE" &
    echo "✅ Widget opened in Chrome"
fi
